"""add api key expiry and password reset throttle

Revision ID: 03c518866193
Revises: 81f82b107bae
Create Date: 2026-09-12 07:20:23.204354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c518866193'
down_revision: Union[str, Sequence[str], None] = '81f82b107bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_password_reset_request_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_reset_request_at')
    op.drop_column('api_keys', 'expires_at')
    # ### end Alembic commands ###
