"""add task position

Revision ID: 2874c4176b5c
Revises: 858dc5106d48
Create Date: 2026-04-25 09:59:21.265390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2874c4176b5c'
down_revision: Union[str, Sequence[str], None] = '858dc5106d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.execute("""
        UPDATE tasks SET position = sub.rn - 1
        FROM (
          SELECT id,
                 ROW_NUMBER() OVER (
                   PARTITION BY COALESCE(story_id::text, 'proj_' || project_id::text)
                   ORDER BY created_at
                 ) as rn
          FROM tasks
        ) sub
        WHERE tasks.id = sub.id
    """)
    op.create_index('ix_task_story_position', 'tasks', ['story_id', 'position'])
    op.create_index('ix_task_project_position', 'tasks', ['project_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_story_position', table_name='tasks')
    op.drop_index('ix_task_project_position', table_name='tasks')
    op.drop_column('tasks', 'position')
    # ### end Alembic commands ###
