"""add missing indexes project owner comment fks task position

Revision ID: 307e81eb1588
Revises: c5f4b656cfd9
Create Date: 2026-06-06 19:35:14.428420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307e81eb1588'
down_revision: Union[str, Sequence[str], None] = 'c5f4b656cfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_project_id', 'comments', ['project_id'], unique=False)
    op.create_index('ix_comment_story_id', 'comments', ['story_id'], unique=False)
    op.create_index('ix_comment_task_id', 'comments', ['task_id'], unique=False)
    op.create_index('ix_projects_owner_id', 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_owner_id', table_name='projects')
    op.drop_index('ix_comment_task_id', table_name='comments')
    op.drop_index('ix_comment_story_id', table_name='comments')
    op.drop_index('ix_comment_project_id', table_name='comments')
    # ### end Alembic commands ###
