"""add_project_id_to_tasks_make_story_id_nullable

Revision ID: 7d0f629b8a5f
Revises: c393321d07db
Create Date: 2026-04-19 07:29:30.037546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0f629b8a5f'
down_revision: Union[str, Sequence[str], None] = 'c393321d07db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tasks', sa.Column('project_id', sa.UUID(), nullable=True))
    op.execute(sa.text(
        "UPDATE tasks SET project_id = stories.project_id "
        "FROM stories WHERE tasks.story_id = stories.id"
    ))
    op.alter_column('tasks', 'project_id', existing_type=sa.UUID(), nullable=False)
    op.alter_column('tasks', 'story_id', existing_type=sa.UUID(), nullable=True)
    op.drop_index(op.f('ix_task_story_status'), table_name='tasks')
    op.create_index('ix_task_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('ix_task_project_status', table_name='tasks')
    op.create_index(op.f('ix_task_story_status'), 'tasks', ['story_id', 'status'], unique=False)
    op.alter_column('tasks', 'story_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###
