"""add user_llm_providers and llm_usage_events

Revision ID: 81f82b107bae
Revises: f633f1a439cc
Create Date: 2026-09-05 19:40:55.616640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f82b107bae'
down_revision: Union[str, Sequence[str], None] = 'f633f1a439cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_usage_event_user_created', 'llm_usage_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_created_at'), 'llm_usage_events', ['created_at'], unique=False)
    op.create_table('user_llm_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_key_hint', sa.String(length=8), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_llm_provider_user_provider')
    )
    op.create_index('ix_user_llm_provider_user_id', 'user_llm_providers', ['user_id'], unique=False)
    op.add_column('users', sa.Column('llm_rpm_ceiling', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('llm_tpm_ceiling', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_tpm_ceiling')
    op.drop_column('users', 'llm_rpm_ceiling')
    op.drop_index('ix_user_llm_provider_user_id', table_name='user_llm_providers')
    op.drop_table('user_llm_providers')
    op.drop_index(op.f('ix_llm_usage_events_created_at'), table_name='llm_usage_events')
    op.drop_index('ix_llm_usage_event_user_created', table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    # ### end Alembic commands ###
