"""add sprints and effort tracking

Revision ID: 858dc5106d48
Revises: 5bb4bdf3b426
Create Date: 2026-04-23 21:40:12.714136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858dc5106d48'
down_revision: Union[str, Sequence[str], None] = '5bb4bdf3b426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sprints_project_id', 'sprints', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('effort_unit', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('effort', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('sprint_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sprint_id')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'effort')
    op.drop_column('projects', 'effort_unit')
    op.drop_index('ix_sprints_project_id', table_name='sprints')
    op.drop_table('sprints')
    # ### end Alembic commands ###
