"""add_email_confirmed_to_users

Revision ID: 9189d3dbf15f
Revises: fb57c93a3ab2
Create Date: 2026-05-10 13:44:38.241064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9189d3dbf15f'
down_revision: Union[str, Sequence[str], None] = 'fb57c93a3ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default='false')
    )
    op.execute("UPDATE users SET email_confirmed = TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###
