"""add user project preferences

Revision ID: c285cfb6a1be
Revises: 2874c4176b5c
Create Date: 2026-04-25 10:39:24.682621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c285cfb6a1be'
down_revision: Union[str, Sequence[str], None] = '2874c4176b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tab_order', sa.JSON(), nullable=False),
    sa.Column('hidden_tabs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project_preferences')
    )
    op.drop_index(op.f('ix_task_project_position'), table_name='tasks')
    op.drop_index(op.f('ix_task_story_position'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_story_position'), 'tasks', ['story_id', 'position'], unique=False)
    op.create_index(op.f('ix_task_project_position'), 'tasks', ['project_id', 'position'], unique=False)
    op.drop_table('user_project_preferences')
    # ### end Alembic commands ###
