"""add key_prefix to api_keys

Revision ID: c5f4b656cfd9
Revises: c15015e0f1e5
Create Date: 2026-06-06 19:20:04.573066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f4b656cfd9'
down_revision: Union[str, Sequence[str], None] = 'c15015e0f1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_prefix', sa.String(length=16), nullable=False, server_default=''))
    op.create_index('ix_api_key_prefix_revoked', 'api_keys', ['key_prefix', 'revoked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_key_prefix_revoked', table_name='api_keys')
    op.drop_column('api_keys', 'key_prefix')
    # ### end Alembic commands ###
